[11:44:57 PM]: Spawning C:\src\flutter\bin\flutter.bat with args ["test","--machine","--name","^Counter increments smoke test( \\(variant: .*\\))?$","--run-skipped","-d","emulator-5554","test\\widget_test.dart"]
[11:44:57 PM]: ..  in C:\Users\jairo\Documents\PCToDriveBackup\GitHub\tull_shopping_cart_app
[11:44:57 PM]: ..  with {"toolEnv":{"FLUTTER_HOST":"VSCode","PUB_ENVIRONMENT":"vscode.dart-code"}}
[11:44:57 PM]: PID: 23728
[11:44:59 PM]: <== {"protocolVersion":"0.1.1","runnerVersion":null,"pid":16376,"type":"start","time":0}
[11:44:59 PM]: <== {"suite":{"id":0,"platform":"vm","path":"C:\\Users\\jairo\\Documents\\PCToDriveBackup\\GitHub\\tull_shopping_cart_app\\test\\widget_test.dart"},"type":"suite","time":0}
[11:44:59 PM]: <== {"test":{"id":1,"name":"loading C:\\Users\\jairo\\Documents\\PCToDriveBackup\\GitHub\\tull_shopping_cart_app\\test\\widget_test.dart","suiteID":0,"groupIDs":[],"metadata":{"skip":false,"skipReason":null},"line":null,"column":null,"url":null},"type":"testStart","time":2}
[11:44:59 PM]: <== {"count":1,"time":10,"type":"allSuites"}
[11:45:00 PM]: <== [{"event":"test.startedProcess","params":{"observatoryUri":null}}]
[11:45:00 PM]: <== {"testID":1,"result":"success","skipped":false,"hidden":true,"type":"testDone","time":1560}
[11:45:00 PM]: <== {"group":{"id":2,"suiteID":0,"parentID":null,"name":"","metadata":{"skip":false,"skipReason":null},"testCount":1,"line":null,"column":null,"url":null},"type":"group","time":1563}
[11:45:00 PM]: <== {"test":{"id":3,"name":"Counter increments smoke test","suiteID":0,"groupIDs":[2],"metadata":{"skip":false,"skipReason":null},"line":159,"column":5,"url":"package:flutter_test/src/widget_tester.dart","root_line":14,"root_column":3,"root_url":"file:///C:/Users/jairo/Documents/PCToDriveBackup/GitHub/tull_shopping_cart_app/test/widget_test.dart"},"type":"testStart","time":1564}
[11:45:01 PM]: <== {"testID":3,"messageType":"print","message":"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════\nThe following CubitUnhandledErrorException was thrown running a test:\nUnhandled error NoSuchMethodError: The method 'add' was called on null.\nReceiver: null\nTried calling: add(Instance of 'ProductCart') occurred in Instance of 'CartBloc'.\n#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:63:5)\n#1      CartBloc._productCartsManager\n(package:tull_shopping_cart_app/blocs/bloc/cart_bloc.dart:47:28)\n#2      CartBloc.mapEventToState (package:tull_shopping_cart_app/blocs/bloc/cart_bloc.dart:21:7)\n<asynchronous suspension>\n#3      StackZoneSpecification._registerUnaryCallback.<anonymous closure>\n(package:stack_trace/src/stack_zone_specification.dart)\n<asynchronous suspension>\n\nWhen the exception was thrown, this was the stack:\n#0      Cubit.onError.<anonymous closure> (package:bloc/src/cubit.dart:144:7)\n#1      Cubit.onError (package:bloc/src/cubit.dart:145:6)\n#2      Bloc.onError (package:bloc/src/bloc.dart:201:11)\n#45     FakeAsync.flushMicrotasks (package:fake_async/fake_async.dart:193:32)\n#46     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1008:26)\n#49     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)\n#50     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:993:27)\n#51     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:554:22)\n#54     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)\n#55     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:551:27)\n#56     main.<anonymous closure> (file:///C:/Users/jairo/Documents/PCToDriveBackup/GitHub/tull_shopping_cart_app/test/widget_test.dart:16:18)\n#57     main.<anonymous closure> (file:///C:/Users/jairo/Documents/PCToDriveBackup/GitHub/tull_shopp…
[11:45:01 PM]: <== {"testID":3,"error":"Test failed. See exception logs above.\nThe test description was: Counter increments smoke test","stackTrace":"","isFailure":false,"type":"error","time":2301}
[11:45:01 PM]: <== {"testID":3,"messageType":"print","message":"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════\nThe following assertion was thrown running a test (but after the test had completed):\nThe finder \"zero widgets with icon \"IconData(U+0E047)\" (ignoring offstage widgets)\" (used in a call\nto \"tap()\") could not find any matching widgets.\n\nWhen the exception was thrown, this was the stack:\n#0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:902:7)\n#1      WidgetController.getCenter (package:flutter_test/src/controller.dart:841:12)\n#2      WidgetController.tap (package:flutter_test/src/controller.dart:273:18)\n#3      main.<anonymous closure> (file:///C:/Users/jairo/Documents/PCToDriveBackup/GitHub/tull_shopping_cart_app/test/widget_test.dart:23:18)\n<asynchronous suspension>\n<asynchronous suspension>\n(elided one frame from package:stack_trace)\n════════════════════════════════════════════════════════════════════════════════════════════════════","type":"print","time":2302}
[11:45:01 PM]: <== {"testID":3,"result":"error","skipped":false,"hidden":false,"type":"testDone","time":2302}
[11:45:01 PM]: <== {"success":false,"type":"done","time":2331}
[11:45:01 PM]: Process terminated! 1, null
